services:
  - type: web
    name: delivery-cruzeiro-api
    runtime: docker
    plan: free
    region: virginia
    branch: main
    healthCheckPath: /health
    autoDeployTrigger: commit
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: info
      - key: DATABASE_URL
        sync: false
      - key: BETTER_AUTH_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: CORS_ORIGIN
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: ABACATEPAY_API_KEY
        sync: false
      - key: ABACATEPAY_API_URL
        value: https://api.abacatepay.com.br
      - key: CLOUDINARY_URL
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_UPLOAD_FOLDER
        value: delivery-cruzeiro
